/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Model.SocialNetwork;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Bastian
 */
public class FollowFrame extends javax.swing.JFrame {
    private LoggedOptionFrame ventanaOpciones;
    private SocialNetwork redSocial;
    /**
     * Creates new form FollowFrame
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFollow = new javax.swing.JButton();
        btnVolverAtras = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUserFollow = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Has seleccionado la opcion follow");

        btnFollow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFollow.setText("Follow!");
        btnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowActionPerformed(evt);
            }
        });

        btnVolverAtras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolverAtras.setText("Volver atras");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setText("Refrescar ventana usuarios");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre usuario a seguir: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserFollow))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserFollow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(btnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public FollowFrame(LoggedOptionFrame ventanaOpciones, SocialNetwork redSocial) {
         initComponents();
        // mostrarUsuariosRedSocial();
         this.setLocationRelativeTo(null);
         this.ventanaOpciones = ventanaOpciones;
         this.redSocial = redSocial;
         
      
      
    }
    
    /**
     * Metodo mostrar usuarios de la red social por pantalla
     * @return void
     */
    private void mostrarUsuariosRedSocial() {
        String usuariosRedSocial = "";
        usuariosRedSocial = usuariosRedSocial + "Usuarios de la red social: " + '\n';
        for(Usuario usuarioActual : redSocial.getUsuariosRedSocial()){
            usuariosRedSocial = usuariosRedSocial + usuarioActual.usuarioToString() + '\n';
        }
        jTextArea1.setText(usuariosRedSocial);
    }
    
    /**
     * Evento refrescar la ventana actual
     * @param evt 
     * @return void
     */
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        mostrarUsuariosRedSocial();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * Evento volver a la ventana anterior
     * @param evt 
     * @return void
     */
    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        this.setVisible(false);
        ventanaOpciones.setVisible(true);
    }//GEN-LAST:event_btnVolverAtrasActionPerformed
    
    /**
     * Evento seguir a un usuario
     * @param evt 
     * @return void
     */
    private void btnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowActionPerformed
       String usuarioAseguir = txtUserFollow.getText(); 
       if("".equals(usuarioAseguir)){
           // JOptionPane.showMessageDialog(this,"Casillas vacias para publicar","Error post",JOptionPane.ERROR_MESSAGE);
           JOptionPane.showMessageDialog(this,"No se ingreso ningun usuario!", "Error follow", JOptionPane.ERROR_MESSAGE);
       }
           
       else{
          if(redSocial.follow(usuarioAseguir)){
              //JOptionPane.showMessageDialog(this, "Se ha hecho la publicacion en el propio muro");
                JOptionPane.showMessageDialog(this,"Se ha seguido al usuario: " + usuarioAseguir + "exitosamente!");
                mostrarUsuariosRedSocial();
                txtUserFollow.setText("");
                
            }
            //caso falso follow    
          else{
                
            JOptionPane.showMessageDialog(this,"No se pudo realizar el follow!", "Error follow", JOptionPane.ERROR_MESSAGE);    
                
                
            }    
                
                
        }
       
           
       
       
    }//GEN-LAST:event_btnFollowActionPerformed

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFollow;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtUserFollow;
    // End of variables declaration//GEN-END:variables

  
}
